%: %.tex *.sty
	latexmk -pdfxe $^
	make clean

clean:
	rm -f *.aux *.bbl *.blg *.idx *.ind *.lof *.lot *.out *.toc *.nav *.acn *.acr *.alg *.glg *.glo *.gls *.ist *.fls *.log *.snm *.fdb_latexmk *.g *.xdv
